name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: mafalda-sfu/workflows/.github/workflows/main-no_coverage.yml@v1

    with:
      node-version: lts/-1
      registry-url: https://npm.pkg.github.com

    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
